site_name: Mohammad Abd El-Fattah
theme :
  name: material
  favicon: favicon.ico
  icon:
   logo: fontawesome/solid/brain
  palette:
    scheme: slate
    primary: black

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/m-abdelfattah-m
    - icon: fontawesome/brands/github
      link: https://github.com/Mohammad-Abd-El-Fattah
      
nav:
  - Home: index.md
  - Cyber Security:
      - 'Start Here':
         - blog/index.md
      - 'Web Application Penetration Testing':
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-08-07-web_security_essential.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-09-18-Command_Injection.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-09-19-Cross_Site_Scripting.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-09-20-File_Inclusion.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-09-21-Server_Side_Request_Forgery.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-09-22-Structured_Query_Language.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-10-03-OS_Injection.md
         - blog/posts/Cyber Security/Web Application Penetration Testing/2024-10-06-Information_Disclosure.md
      - 'Cryptography':
         - blog/posts/Cyber Security/Cryptography/2024-1-07-exploring_caesar_cipher_encryption_and_decryption.md
  - Computer Science:
      - 'Start Here':
         - blog/CS.md
      - 'Object Oriented Programming':
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-12-28-Complex_Class.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Study_Estimates_System.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Adding_Elements_of_a_2D_Array.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Area_Of_Circle_Calcalte.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Calculating_the_Factorial_of_a_Number.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Finding_the_Biggest_Number_Between_Two_Values.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Function_Overloading.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Insurance_Eligibility_System.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Math_Functions.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Number_Checker.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Separating_Even_and_Odd_Numbers_in_an_Array.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Study_Estimates_System.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Summing_Elements_of_a_Matrix.md
         - blog/posts/Computer Science/Programming/Object Oriented Programming/2023-03-29-Summing_Matrix_Corners_and_Crosses.md
      - 'Data Structure':
         - blog/posts/Computer Science/Programming/Data Structure/2024-01-04-delving_deeper_into_factorials.md
         - blog/posts/Computer Science/Programming/Data Structure/2024-01-05-unraveling_the_fibonacci_sequence.md
         - blog/posts/Computer Science/Programming/Data Structure/2024-01-06-finding_common_ground_with_recursion.md
         - blog/posts/Computer Science/Programming/Data Structure/2024-01-06-multiplying_with_recursive_twists.md    
      - 'Database':
         - blog/posts/Computer Science/Database/2024-01-27-data_definition_language.md
         - blog/posts/Computer Science/Database/2024-01-27-data_manipulation_language.md
         - blog/posts/Computer Science/Database/2024-02-07-general_knowledge_in_database.md
         - blog/posts/Computer Science/Database/2024-03-16-entity_relationship_diagram.md
         - blog/posts/Computer Science/Database/2024-03-16-entity_relationship_diagram.md
         - blog/posts/Computer Science/Database/2024-03-23-data_control_language.md
         - blog/posts/Computer Science/Database/2024-03-16-entity_relationship_diagram.md   
  - About:
    - About Me : About/about.md
    - Project : About/Projects.md
  - Tags: tags.md

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog #:
         #- blog_dir: blog/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Copyright &copy; 2024 Mohammad Abd El-Fattah